Algoritmo "Exercicio 4"

//Verifica o que será impresso na tela ao serem executados

Var
// Seção de Declarações das variáveis 
a, b, c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a <- 10
b <- a + 1 //b passa a valer 11
escreval(b)
a <- b + 1 // a passa a valer 12
escreval(a)
b <- a + 1 // b passa a valer 13
escreval(b)
escreval(a) // valor de a é 12
a <- b + 1 //a passa a valer 14
escreval(a, b) // o valor de a é 14 e b 13

Fimalgoritmo