Algoritmo "Exercicio 3"

//Verifica o que será impresso na tela ao serem executados

Var
// Seção de Declarações das variáveis 
a, b, c, d, eh, f: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a <- (4 / 2) + (2 / 4) //2.5
b <- 4 /(2 + 2) / 4 //0.25
c <- (4 + 2) * 2 - 4 //8
d <- 4 / 2 + 2 / 4 //2.5
eh <- 4 / 2 + 2 / 4 //2.5
f <- 4 + 2 * 2 - 4 //4

escreval(a)
escreval(b)
escreval(c)
escreval(d)
escreval(eh)
escreval(f)

Fimalgoritmo