Algoritmo "Exercicio 2"

//Troca de valores


Var
// Seção de Declarações das variáveis 
a, b, c: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
a <- 10
b <- 20
c <- a + b
escreval(c)//primeiro valor de c
b <- 10 //novo valor de b
escreval(b,c)// exibindo seus novos valores
c <- a + b // c agora recebe a soma de a e b
escreval(a, b , c)// a e b passa a ter os mesmos valores e c passa a ser 20

Fimalgoritmo