Algoritmo "Exercicio 2f"

//Verificar o que será impresso na tela ao serem executados

Var
// Seção de Declarações das variáveis 
x, y, z:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x <- 1
y <- 2
z <- y - x//z recebe valor de y - x = 1
escreval(z) //apresentado o novo valor de z = 1
x <- 5 //x recebe novo valor
y <- x + z //y recebe novo valor de x + z = 6
escreva(y) //exibindo novo valor y

Fimalgoritmo